spring.application.name=pathlabmaster
server.port=8088
spring.datasource.url=jdbc:postgresql://ep-odd-sky-a4p0w4i9-pooler.us-east-1.aws.neon.tech/pathlabmaster?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lbDwv6oyU4si
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver